version: '3'
services:

    php-apache:
        container_name: php-apache 
        build: ./googleTrends
        volumes:
            - ./googleTrends:/var/www/html
        environment:
          - MYSQL_DBHOST=db 
          - MYSQL_DAPORT=9000
          - MYSQL_DAUSER=root
          - MYSQL_DAPASS=root
          - MYSQL_DANAME=
        
        ports:
            - 8000:80
        depends_on:
            - db
  
    db:
      image: mysql:latest
      container_name: db
      restart : always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test 
      ports:
        - "9000:3306"
      volumes:
        - db_data:/var/lib/mysql

    phpmyadmin : 
      image : phpmyadmin:latest
      restart : always 
      ports:
        - 8080:80 
      environment : 
        PMA_HOST: db
      depends_on:
        - db


    python-app:
        container_name: PythonScript
        build: ./GTscript
        depends_on:
          - db
        environment:
          - MYSQL_DBHOST=db 
          - MYSQL_DAPORT=9000
          - MYSQL_DAUSER=root
          - MYSQL_DAPASS=root
          - MYSQL_DANAME=
          
        command: python script.py

volumes:
  db_data: